"""
app/services/report_builder.py
DOCX report generation engine — Sterling Stormwater Maintenance Services template.

Fix log (applied in this version):
  #1  Cover logo 20% larger (3.0 → 3.6")
  #2  Green bars: black overline/underline, 50% thinner (before=1,after=1), black text
  #3  Section bar text is black (handled in #2)
  #4  Footer font 10 pt (was 8)
  #5  Info tables: no outer L/R borders (_apply_table_style_no_outer_vborders)
  #6  Cover page: compact spacing helpers so everything fits on page 1
  #8  Photo page rules black; black rule added below photo grid
  #9  build_report accepts photo_grid param; 2x2 / 2x3 / 3x3 grid implementations
  #10 _get_display_size() constrains portrait photos to cell height
  #11 Photo page header: logo only — no right-side title text
  #12 Photo logo 2x larger (1.5 → 3.0")
"""

import io
from pathlib import Path
from collections import defaultdict
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

from app.session import ProjectSession
from app.services.photo_service import resize_for_report
from app.services.page_fit import apply_page_fit, PageLayout, BODY_HEIGHT_PT

# ── Per-build cover layout state ──────────────────────────────────────────────
# Populated by build_report() before the cover page is constructed.
# Cover-page helper functions read adjusted values through _cl() below.
_COVER_LAYOUT: dict = {}
_COVER_FIT_RESULT = None   # PageFitResult — set in build_report, used to bottom-align cert


def _cl(key: str, default):
    """Return the current cover-layout value for key, falling back to default."""
    return _COVER_LAYOUT.get(key, default)

# ── Output directory ──────────────────────────────────────────────────────────
OUTPUT_DIR = Path("output")

# ── Style configuration (public — other modules may import this) ───────────────
STYLE_CONFIG = {
    "font_body":            "Calibri",
    "font_heading":         "Calibri",
    "font_caption":         "Calibri",          # Fix: was Arial Black
    "font_size_body":       8.5,
    "font_size_h1":         11,
    "font_size_h2":         11,
    "font_size_h3":         10,
    "color_primary":        RGBColor(0x1A, 0xB7, 0x38),
    "color_secondary":      RGBColor(0x14, 0x8A, 0x2A),
    "color_accent":         RGBColor(0x1A, 0xB7, 0x38),
    "color_text":           RGBColor(0x1A, 0x1A, 0x1A),
    "color_light_gray":     RGBColor(0xF2, 0xF2, 0xF2),
    "page_margin_side_inches":   0.5,
    "page_margin_top_inches":    0.61,
    "page_margin_bottom_inches": 0.5,
    "photo_width_inches":        6.0,
    "photo_two_col_width_inches": 3.0,
}

# ── Company constants ─────────────────────────────────────────────────────────
_COMPANY_NAME  = "Sterling Stormwater Maintenance Services, Inc"
_COMPANY_EMAIL = "support@sterlingstormwater.com"
_CERT_TITLE    = "Stormwater Compliance Specialist"
_STERLING_GREEN = "1AB738"

_LOGO_PATH = Path(__file__).parent.parent.parent / "assets" / "sterling_logo.png"

# ── Logo size constants ───────────────────────────────────────────────────────
_COVER_LOGO_WIDTH    = 3.6   # Fix #1: 20% larger than original 3.0"
_PHOTO_LOGO_WIDTH    = 3.0   # Fix #12: 2× original 1.5" on photo pages
_INTERIOR_LOGO_WIDTH = 1.5   # Interior page headers (unchanged)

# ── True printable body height — single source of truth ──────────────────────
# BODY_HEIGHT_PT is defined in page_fit.py and imported here so both modules
# use the same value.  The footer lives inside the bottom margin and does NOT
# consume body space; page_fit.PageLayout.footer_height_in is 0.0 for the same
# reason.  See page_fit.py for the derivation.
_BODY_HEIGHT_PT = BODY_HEIGHT_PT   # (11.0 − 0.61 − 0.50) × 72 = 712.08 pt

# ── Photo grid configurations ─────────────────────────────────────────────────
# Fix #9/#10: per-grid layout math
#   col_w     = table column cell width (inches)
#   photo_w   = image display width (inches; slightly less than col_w for cell padding)
#   photo_h_max = max image display height (inches; prevents portrait overflow)
#   per_page  = cols × rows (photos per physical page)
_GRID_CFG = {
    "2x2": {"cols": 2, "rows": 2, "per_page": 4, "col_w": 3.70, "photo_w": 3.50, "photo_h_max": 3.55},
    "2x3": {"cols": 2, "rows": 3, "per_page": 6, "col_w": 3.70, "photo_w": 3.50, "photo_h_max": 2.05},
    "3x3": {"cols": 3, "rows": 3, "per_page": 9, "col_w": 2.40, "photo_w": 2.20, "photo_h_max": 1.85},
}

# ── Static boilerplate text ───────────────────────────────────────────────────
_INTRO_TEXT = (
    "This report has been generated by STERLING Stormwater Maintenance Services, LLC. "
    "The information provided in this report is not an evaluation as to the performance "
    "of the stormwater systems and STERLING Stormwater Maintenance Services accepts no "
    "responsibility relating to the performance of these systems. This information is "
    "provided solely as an assessment of the condition of the stormwater systems as it "
    "pertains to maintenance. Recommendations and next actions are based on the "
    "manufacturer\u2019s published literature or the generally accepted practice if applicable."
)

_CERT_TEXT = (
    "This hereby certifies that the information contained in this report is accurate "
    "and was obtained using accepted industry practices."
)

_SUMMARY_PLACEHOLDER = "[Insert overall summary here]"

_REPORT_TITLE = {
    "Inspection":                 "Stormwater Facility Inspection Report",
    "Maintenance":                "Stormwater System Maintenance Report",
    "Inspection and Maintenance": "Stormwater System and Maintenance Report",
}

_FINDINGS_BAR = {
    "Inspection":                 "INSPECTION FINDINGS",
    "Maintenance":                "INSPECTION AND MAINTENANCE SUMMARY",
    "Inspection and Maintenance": "INSPECTION AND MAINTENANCE SUMMARY",
}

_FINDINGS_OPENER = (
    "An inspection of the above referenced stormwater components was performed on "
    "{inspection_date}. The results of the inspection revealed the following:"
)


# ══════════════════════════════════════════════════════════════════════════════
# Public entry point
# ══════════════════════════════════════════════════════════════════════════════

def build_report(proj: ProjectSession, filename: str,
                 template_path: str = "",
                 photo_grid: str = "2x3") -> str:
    """
    Build the Sterling DOCX report and write it to OUTPUT_DIR/filename.

    Args:
        proj:          ProjectSession with all report data.
        filename:      Output filename (saved to OUTPUT_DIR).
        template_path: Unused in v2 (kept for API compatibility).
        photo_grid:    Grid layout — "2x2", "2x3" (default), or "3x3".

    Returns absolute path of saved file.
    """
    OUTPUT_DIR.mkdir(exist_ok=True)
    # Validate grid; fall back to default
    if photo_grid not in _GRID_CFG:
        photo_grid = "2x3"

    # ── Run page-fit algorithm and populate cover layout ──────────────────────
    global _COVER_FIT_RESULT
    fit_result = apply_page_fit(proj)
    _COVER_FIT_RESULT = fit_result
    L = fit_result.layout
    _COVER_LAYOUT.update({
        "body_size_pt":       L.body_size_pt,
        "logo_width_in":      L.logo_width_in,
        "logo_after_pt":      L.logo_after_pt,
        "title_size_pt":      L.title_size_pt,
        "title_before_pt":    L.title_before_pt,
        "title_after_pt":     L.title_after_pt,
        "bar_before_pt":      L.bar_before_pt,
        "bar_after_pt":       L.bar_after_pt,
        "bar_spacer_pt":      L.bar_spacer_pt,
        "body_before_pt":     L.body_before_pt,
        "body_after_pt":      L.body_after_pt,
        "subhead_before_pt":  L.subhead_before_pt,
        "subhead_after_pt":   L.subhead_after_pt,
        "table_cell_pad_pt":  L.table_cell_pad_pt,
        "cert_sig_before_pt": L.cert_sig_before_pt,
        "cert_sig_after_pt":  L.cert_sig_after_pt,
        "intro_after_pt":     L.intro_after_pt,
        # Page-count metadata for the cover table
        "photo_grid":  photo_grid,
        "n_photos":    len(proj.photos),
    })
    # Optionally surface fit diagnostics in the log
    import logging
    _log = logging.getLogger(__name__)
    _log.debug(fit_result.debug_summary())
    # ── Diagnostic: print page-fit results to terminal so we can calibrate ────
    print(fit_result.debug_summary())

    doc = Document()
    _configure_document(doc)

    _build_cover_page(doc, proj)
    _add_footer(doc.sections[0])

    # NOTE: Interior body pages (_build_inspection_body etc.) are intentionally
    # NOT called here.  The cover page already contains all findings content —
    # calling them again would duplicate every findings section.  The functions
    # are kept in this file for reference but are not part of the build flow.

    if proj.photos:
        _build_photo_section(doc, proj, grid_type=photo_grid)

    for section in doc.sections[1:]:
        _add_footer(section)

    out_path = OUTPUT_DIR / filename
    doc.save(str(out_path))
    return str(out_path)


# ══════════════════════════════════════════════════════════════════════════════
# Document-level configuration
# ══════════════════════════════════════════════════════════════════════════════

def _configure_document(doc: Document):
    side   = Inches(STYLE_CONFIG["page_margin_side_inches"])
    top    = Inches(STYLE_CONFIG["page_margin_top_inches"])
    bottom = Inches(STYLE_CONFIG["page_margin_bottom_inches"])
    for section in doc.sections:
        section.top_margin    = top
        section.bottom_margin = bottom
        section.left_margin   = side
        section.right_margin  = side

    style = doc.styles["Normal"]
    style.font.name = STYLE_CONFIG["font_body"]
    style.font.size = Pt(STYLE_CONFIG["font_size_body"])


# ══════════════════════════════════════════════════════════════════════════════
# Cover page  (Fix #6: compact spacing throughout to guarantee single-page fit)
# ══════════════════════════════════════════════════════════════════════════════

def _build_cover_row1_content(body, proj: ProjectSession):
    """
    Outer-table Row 0 content: logo + report title + GENERAL INFORMATION bar + info table.
    `body` accepts Document or Cell (duck-typed).
    """
    meta = proj.meta
    rt   = meta.report_type

    # 1. Logo
    logo_para = body.add_paragraph()
    logo_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_spacing(logo_para, before=0, after=_cl("logo_after_pt", 4))
    logo_run = logo_para.add_run()
    if _LOGO_PATH.exists():
        logo_run.add_picture(str(_LOGO_PATH), width=Inches(_cl("logo_width_in", _COVER_LOGO_WIDTH)))
    else:
        logo_run.text = _COMPANY_NAME
        _style_run(logo_run, bold=True, size=16, color=STYLE_CONFIG["color_primary"])

    # 2. Report title
    title_para = body.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_spacing(title_para,
                 before=_cl("title_before_pt", 2),
                 after=_cl("title_after_pt", 6))
    title_run = title_para.add_run(_REPORT_TITLE.get(rt, "Stormwater System Report"))
    _style_run(title_run, bold=True, size=_cl("title_size_pt", 14))

    # 3. GENERAL INFORMATION bar
    _add_green_bar(body, "GENERAL INFORMATION")

    # 4. Cover info table
    _build_cover_info_table(body, proj)


def _build_cover_row2_content(body, proj: ProjectSession):
    """
    Outer-table Row 1 content: INTRODUCTION bar + intro text + FINDINGS bar + write-ups.
    `body` accepts Document or Cell (duck-typed).
    """
    meta = proj.meta
    rt   = meta.report_type

    # 5. INTRODUCTION bar
    _add_green_bar(body, "INTRODUCTION")

    # 6. Intro boilerplate
    intro_para = body.add_paragraph()
    intro_para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    _set_spacing(intro_para, before=0, after=_cl("intro_after_pt", 2))
    intro_run = intro_para.add_run(_INTRO_TEXT)
    _style_run(intro_run, size=8.0)

    # 7. Findings / summary bar
    bar_label = _FINDINGS_BAR.get(rt, "INSPECTION AND MAINTENANCE SUMMARY")
    _add_green_bar(body, bar_label)

    # 8. Per-system write-ups
    if rt == "Inspection":
        _add_cover_inspection_findings(body, proj)
    else:
        _add_cover_maintenance_summary(body, proj)


def _estimate_row1_height_pt(proj: ProjectSession) -> float:
    """
    Estimate height of outer-table Row 0 (logo + title + GENERAL INFORMATION + info table).
    Intentionally a slight over-estimate so content is never clipped; any slack
    appears as invisible white space at the bottom of Row 0.
    """
    # Logo
    try:
        from PIL import Image as _PILImg
        img    = _PILImg.open(str(_LOGO_PATH))
        w_px, h_px = img.size
        aspect = w_px / max(h_px, 1)
    except Exception:
        aspect = 3.296
    logo_w = _cl("logo_width_in", _COVER_LOGO_WIDTH)
    logo_h = (logo_w / aspect) * 72.0 + _cl("logo_after_pt", 4)

    # Title
    title_sz = _cl("title_size_pt", 14)
    title_h  = title_sz * 1.2 + _cl("title_before_pt", 2) + _cl("title_after_pt", 6)

    # GENERAL INFORMATION bar
    bar_h = 14.0

    # Cover info table (3 rows, min-height driven by right-column BMP lines)
    body_sz    = _cl("body_size_pt", STYLE_CONFIG["font_size_body"])
    cp         = _cl("table_cell_pad_pt", 1)
    line_h     = body_sz * 1.2 + 2 * cp
    bmp_lines  = _bmp_summary_lines(proj)
    right_lines = 1 + len(bmp_lines)
    row_min    = max(18.0, (right_lines * line_h) / 3)
    table_h    = 3 * row_min

    return logo_h + title_h + bar_h + table_h + 4.0   # +4 pt safety


def _estimate_cert_height_pt() -> float:
    """
    Conservative over-estimate of outer-table Row 2 height.

    Actual content (measured from _build_cert_section / _build_certification_table):
      CERTIFICATION bar          ≈ 14 pt  (10pt text × 1.2 lhf, zero cell padding)
      cert table row 0 (text)    ≈ 22 pt  (2 lines × line_h + 2×cp)
      cert table row 1 (names)   ≈ 33 pt  (3 lines × line_h + 2×cp)
      cert table row 2 (sig)     ≈ 34 pt  (line_h + sig_before + sig_after)
      cert table border overhead ≈  6 pt  (_apply_table_style_no_outer_vborders
                                            adds top/insideH×2/bottom borders at
                                            sz=12; each border ≈ 1.5 pt rendered)
      bottom green bar           ≈ 16 pt  (before=2, line, after=2)
    Raw sub-total                ≈ 125 pt

    Safety margin                  23 pt  — absorbs Word rendering variance,
                                            any paragraph spacing that differs
                                            from our model, and cell-margin
                                            defaults inherited from the table style.

    Row 2's cell uses w:vAlign="bottom" so cert content anchors to the cell
    bottom even when row2_h > actual cert height; surplus space appears ABOVE
    cert (inside row 2 cell), which is invisible white space.
    """
    body_sz = _cl("body_size_pt", STYLE_CONFIG["font_size_body"])
    cp      = _cl("table_cell_pad_pt", 1)
    line_h  = body_sz * 1.2

    cert_bar_h = 14.0                              # CERTIFICATION green bar

    row0_h = 2 * line_h + 2 * cp                  # cert statement — 2 lines
    row1_h = 3 * line_h + 2 * cp                  # company/preparer/title — 3 lines
    sig_before = _cl("cert_sig_before_pt", 12)
    sig_after  = _cl("cert_sig_after_pt",  12)
    row2_h = line_h + sig_before + sig_after        # signature row

    border_overhead = 6.0                          # top + 2×insideH + bottom borders
    cert_table_h    = row0_h + row1_h + row2_h + border_overhead

    green_bar_h  = 16.0                            # bottom green bar

    raw_estimate  = cert_bar_h + cert_table_h + green_bar_h
    safety_margin = 23.0
    return raw_estimate + safety_margin


def _build_cert_section(body, meta):
    """
    Full Certification block: CERTIFICATION bar + cert table + bottom green bar.
    Treated as one anchored unit — the flexible spacer goes ABOVE this entire
    block in _build_cover_page so the whole block lands at the body bottom.
    `body` accepts Document or Cell (duck-typed).
    """
    # 9. CERTIFICATION bar
    _add_green_bar(body, "CERTIFICATION")

    # 10. Certification table
    _build_certification_table(body, meta)

    # 11. Bottom green bar — final visual anchor, stays with cert as one unit
    _add_thick_green_footer_bar(body)


def _build_cover_page(doc: Document, proj: ProjectSession):
    """
    3-zone layout using a full-body-height borderless outer table:

      Row 0  fixed   logo + title + GENERAL INFORMATION bar + info table
      Row 1  flex    INTRODUCTION bar + intro text + FINDINGS bar + write-ups
      Row 2  fixed   CERTIFICATION bar + cert table + bottom green bar

    Row heights sum to exactly _BODY_HEIGHT_PT so Row 2 (cert) is always
    anchored at the body bottom — no calibration constant needed.

    WHY FLAT-FLOW BUILD THEN XML REARRANGE:
      python-docx Cell.add_table() can scramble paragraph order inside a cell
      because add_p_before() searches ALL descendants for the last <w:p>,
      sometimes landing inside a nested table instead of at the cell level.
      Building everything in flat document flow (where Document.add_table()
      has no ordering bug) and then moving the XML elements into table cells
      sidesteps the issue entirely.  Image relationships stay valid because
      the content never leaves the same Document part.
    """
    body_el = doc.element.body

    # ── Phase 1: build all content in flat doc flow ────────────────────────────
    # Snapshot which elements exist BEFORE we start (typically the blank
    # initial <w:p> and the <w:sectPr> that python-docx puts into every new
    # Document body).
    #
    # IMPORTANT: use lxml element identity (set of elements), NOT id().
    # lxml wraps C-level xmlNode objects in transient Python objects; id()
    # returns the Python wrapper's memory address, which can be recycled by
    # the garbage collector after the wrapper is released.  Using a set of
    # the element objects themselves relies on lxml's __hash__ / __eq__,
    # both of which compare the stable underlying C-pointer, so the identity
    # survives across multiple list() calls and GC cycles.
    _pre_existing = set(body_el)   # ← holds refs → wrappers stay alive too

    _build_cover_row1_content(doc, proj)
    _snap0     = list(body_el)
    _snap0_set = set(_snap0)       # ← same: keep refs alive

    _build_cover_row2_content(doc, proj)
    _snap1     = list(body_el)
    _snap1_set = set(_snap1)

    _build_cert_section(doc, proj.meta)
    _snap2 = list(body_el)

    # ── Phase 2: classify elements by destination row ─────────────────────────
    row0_elems = [e for e in _snap0 if e not in _pre_existing]
    row1_elems = [e for e in _snap1 if e not in _snap0_set]
    row2_elems = [e for e in _snap2 if e not in _snap1_set]

    # ── Phase 3: compute exact row heights ────────────────────────────────────
    # _TABLE_OVERHEAD_PT: budget for (a) the 1-pt leading paragraph left in
    # body by Phase 4, (b) Word's table rendering overhead, (c) twip-rounding.
    # 8 pt provides ~7 pt of buffer beyond the 1-pt blank para.
    _TABLE_OVERHEAD_PT = 8.0
    row0_h = _estimate_row1_height_pt(proj)
    row2_h = _estimate_cert_height_pt()        # conservative — includes safety margin
    row1_h = max(20.0, _BODY_HEIGHT_PT - _TABLE_OVERHEAD_PT - row0_h - row2_h)

    print(f"[cover-table] row0={row0_h:.1f}  row1={row1_h:.1f}  "
          f"row2={row2_h:.1f}  total={row0_h + row1_h + row2_h:.1f}  "
          f"body={_BODY_HEIGHT_PT:.1f}  overhead={_TABLE_OVERHEAD_PT:.1f}")

    # ── Phase 4: remove content elements from body ────────────────────────────
    for elem in row0_elems + row1_elems + row2_elems:
        body_el.remove(elem)

    # Minimize any pre-existing blank paragraphs to 1 pt exact height instead
    # of removing them.  Removal risks destroying the <w:sectPr> node (which
    # may be embedded in a <w:p> depending on the python-docx template version),
    # leaving doc.sections[] empty and crashing doc.add_table().  A 1-pt
    # minimized paragraph is visually invisible and is already budgeted for
    # in _TABLE_OVERHEAD_PT above.
    #
    # CRITICAL: We must also collapse the paragraph's font to 1 pt.
    # Word enforces a minimum line height equal to the rendered font ascender +
    # descender, so a paragraph whose Normal style specifies 8.5 pt Calibri will
    # render at ~8–9 pt even when w:lineRule="exact" w:line="20" is set.
    # Without the font collapse the blank para consumes ~8 pt, not 1 pt, and the
    # outer table total overshoots the body height by ~4–5 pt — enough to push
    # the Certification row (Row 2) onto page 2.
    for elem in list(body_el):
        if elem in _pre_existing and elem.tag == qn("w:p"):
            has_text = bool(elem.findall(f".//{qn('w:t')}"))
            if not has_text:
                _pPr = elem.get_or_add_pPr()
                # ── spacing: exact 1 pt line, no before/after ────────────────
                for _sp in list(_pPr):
                    if _sp.tag == qn("w:spacing"):
                        _pPr.remove(_sp)
                _sp = OxmlElement("w:spacing")
                _sp.set(qn("w:before"),   "0")
                _sp.set(qn("w:after"),    "0")
                _sp.set(qn("w:line"),     "20")   # 20 twips = 1 pt
                _sp.set(qn("w:lineRule"), "exact")
                _pPr.append(_sp)
                # ── font: collapse to 1 pt so Word's minimum-height floor ────
                # doesn't expand the line beyond what we declared above.
                _rPr = _pPr.find(qn("w:rPr"))
                if _rPr is None:
                    _rPr = OxmlElement("w:rPr")
                    _pPr.append(_rPr)
                for _tag in ("w:sz", "w:szCs"):
                    _existing_sz = _rPr.find(qn(_tag))
                    if _existing_sz is not None:
                        _rPr.remove(_existing_sz)
                    _sz = OxmlElement(_tag)
                    _sz.set(qn("w:val"), "2")   # 2 half-points = 1 pt
                    _rPr.append(_sz)

    # ── Phase 5: create borderless outer layout table ─────────────────────────
    # Phase 4's guard preserved <w:sectPr> in body, so doc.sections[-1] is
    # intact and doc.add_table() can safely read _block_width from it.
    outer = doc.add_table(rows=3, cols=1)
    _remove_table_borders(outer)
    _set_table_full_width(outer)
    # Explicitly zero table-level cell spacing (w:tblCellSpacing) so the
    # inherited table style does not add hidden inter-row height.
    _zero_table_cell_spacing(outer)

    for row, h in [(outer.rows[0], row0_h),
                   (outer.rows[1], row1_h),
                   (outer.rows[2], row2_h)]:
        _set_row_min_height(row, h, rule="exact")
        _zero_all_cell_margins(row.cells[0])

    # Row 2 cert cell: anchor content to the BOTTOM of the cell.
    # row2_h is intentionally larger than the actual cert content to guarantee
    # it always fits.  vAlign="bottom" places cert at the cell bottom so the
    # surplus white space appears ABOVE cert (between row 1 and cert), not
    # below cert (which would push it away from the footer boundary).
    _cert_tc   = outer.rows[2].cells[0]._tc
    _cert_tcPr = _cert_tc.get_or_add_tcPr()
    _va_existing = _cert_tcPr.find(qn("w:vAlign"))
    if _va_existing is not None:
        _cert_tcPr.remove(_va_existing)
    _va = OxmlElement("w:vAlign")
    _va.set(qn("w:val"), "bottom")
    _cert_tcPr.append(_va)

    # ── Phase 6: inject content into cells ────────────────────────────────────
    _inject_into_cell(outer.rows[0].cells[0], row0_elems)
    _inject_into_cell(outer.rows[1].cells[0], row1_elems)
    _inject_into_cell(outer.rows[2].cells[0], row2_elems)

    # ── Phase 7: collapse trailing body paragraph ─────────────────────────────
    _minimize_trailing_para(doc)


# ── Cover info table ──────────────────────────────────────────────────────────

def _build_cover_info_table(body, proj: ProjectSession):
    """
    3-column info table.  `body` accepts Document or Cell.
    Columns: label | value | BMP summary (merged across all rows).
    """
    meta = proj.meta

    # Page count = 1 cover + ceil(n_photos / per_page) photo sheets
    import math as _math
    _pg   = _cl("photo_grid", "2x3")
    _pp   = _GRID_CFG.get(_pg, _GRID_CFG["2x3"])["per_page"]
    _npho = _cl("n_photos", 0)
    _n_photo_pages = _math.ceil(_npho / _pp) if _npho > 0 else 0
    _page_count = str(1 + _n_photo_pages)

    rows_lv = [
        ("Site Name & Location:",
         (meta.site_name or "") + (f", {meta.site_address}" if meta.site_address else "")),
        ("Inspection Performed By:", meta.prepared_by or ""),
        ("Number of Pages in Report:", _page_count),
    ]

    bmp_lines = _bmp_summary_lines(proj)
    n_rows    = len(rows_lv)

    table = body.add_table(rows=n_rows, cols=3)
    _apply_table_style_no_outer_vborders(table)
    _set_table_full_width(table)      # Fix: span full 7.5" usable width

    # Column widths scaled to fill 7.5" (was 6.5" total — now proportionally expanded)
    col_widths = [Inches(2.0), Inches(3.2), Inches(2.3)]
    for row in table.rows:
        for ci, w in enumerate(col_widths):
            row.cells[ci].width = w

    body_sz = _cl("body_size_pt", STYLE_CONFIG["font_size_body"])
    cp      = _cl("table_cell_pad_pt", 1)

    for i, (label, value) in enumerate(rows_lv):
        lbl_cell = table.cell(i, 0)
        lbl_para = lbl_cell.paragraphs[0]
        lbl_para.alignment = WD_ALIGN_PARAGRAPH.CENTER   # Fix: center text in column
        _set_spacing(lbl_para, before=cp, after=cp)
        _style_run(lbl_para.add_run(label), bold=True, size=body_sz)
        _center_cell_vertical(lbl_cell)                  # Fix: vertical center

        val_cell = table.cell(i, 1)
        val_para = val_cell.paragraphs[0]
        val_para.alignment = WD_ALIGN_PARAGRAPH.CENTER   # Fix: center text in column
        _set_spacing(val_para, before=cp, after=cp)
        _style_run(val_para.add_run(value), size=body_sz)
        _center_cell_vertical(val_cell)                  # Fix: vertical center

    # Merge right column across all rows
    merged = table.cell(0, 2).merge(table.cell(n_rows - 1, 2))
    hdr_para = merged.paragraphs[0]
    hdr_para.alignment = WD_ALIGN_PARAGRAPH.CENTER       # Fix: center text in column
    _set_spacing(hdr_para, before=cp, after=cp)
    _style_run(hdr_para.add_run("Number & Type of Stormwater Components Inspected:"),
               bold=True, size=body_sz)
    _center_cell_vertical(merged)                        # Fix: vertical center

    if bmp_lines:
        for line in bmp_lines:
            p = merged.add_paragraph()
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER      # Fix: center text in column
            _set_spacing(p, before=0, after=0)
            _style_run(p.add_run(line), size=body_sz)
    else:
        p = merged.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        _style_run(p.add_run("(None listed)"), italic=True, size=body_sz)

    # ── Column divider: right border on col 1 only ───────────────────────────
    # insideV is hidden globally; restore exactly the one vertical line that
    # separates the value column from the BMP-summary merged column.
    for i in range(n_rows):
        _add_cell_right_border(table.cell(i, 1))

    # ── Dynamic row-height equalization ──────────────────────────────────────
    # The right merged column may contain more lines than n_rows of left content.
    # Set an `atLeast` min height on each row so the horizontal dividers line up.
    # Line height = font size × 1.2 + 2×spacing overhead per paragraph.
    line_h_pt   = body_sz * 1.2 + 2 * cp
    right_lines = 1 + len(bmp_lines)            # header line + BMP count lines
    right_total = right_lines * line_h_pt
    row_min_pt  = max(18.0, right_total / n_rows)
    for row in table.rows:
        _set_row_min_height(row, row_min_pt)


def _bmp_summary_lines(proj: ProjectSession) -> list:
    lines  = []
    by_type = defaultdict(list)
    for s in proj.systems:
        if s.system_type:
            by_type[s.system_type].append(s)
    for stype, entries in by_type.items():
        count = len(entries)
        ids   = [e.system_id for e in entries if e.system_id]
        if ids and count == 1:
            lines.append(f"({count}) {stype} (BMP# {ids[0]})")
        elif ids:
            lines.append(f"({count}) {stype} (BMP# {', '.join(ids)})")
        else:
            lines.append(f"({count}) {stype}")
    return lines


# ── Cover findings / summary (compact versions) ───────────────────────────────

def _add_cover_inspection_findings(body, proj: ProjectSession):
    meta   = proj.meta
    opener = _FINDINGS_OPENER.format(
        inspection_date=meta.inspection_date or "[date not set]"
    )
    op = body.add_paragraph()
    _set_spacing(op, before=_cl("body_before_pt", 0), after=_cl("body_after_pt", 2))
    _style_run(op.add_run(opener), size=_cl("body_size_pt", STYLE_CONFIG["font_size_body"]))

    if not proj.systems:
        _add_cover_body_para(body, "No systems recorded.")
        return

    for entry in proj.systems:
        wu = proj.write_ups.get(entry.entry_id)
        sub = entry.display_name or entry.system_type
        if entry.notes:
            sub += f" - {entry.notes}"
        _add_cover_system_subheading(body, sub)
        if wu and wu.findings:
            _add_cover_body_para(body, wu.findings)
        if wu and wu.recommendations:
            _add_cover_body_para(body, wu.recommendations)


def _add_cover_maintenance_summary(body, proj: ProjectSession):
    meta         = proj.meta
    rt           = meta.report_type
    exec_summary = getattr(meta, "executive_summary", "") or ""
    summary_text = exec_summary or meta.site_description or _SUMMARY_PLACEHOLDER
    _add_cover_body_para(body, summary_text)

    if not proj.systems:
        return

    for entry in proj.systems:
        wu  = proj.write_ups.get(entry.entry_id)
        sub = entry.display_name or entry.system_type
        if entry.notes:
            sub += f" - {entry.notes}"
        _add_cover_system_subheading(body, sub)
        if rt == "Inspection and Maintenance" and wu and wu.findings:
            _add_cover_body_para(body, wu.findings)
        if wu and wu.maintenance_performed:
            _add_cover_body_para(body, wu.maintenance_performed)
        if wu and wu.post_service_condition:
            _add_cover_body_para(body, wu.post_service_condition)


# ── Cert bottom-alignment ─────────────────────────────────────────────────────

def _align_cert_to_bottom(doc: Document):
    """
    Insert a vertical spacer before the CERTIFICATION section so that it
    lands at the bottom of page 1.

    Strategy:
      - The page-fit algorithm already estimated total content height (used_pt)
        and the available printable height (available_pt).
      - If the content fits (used_pt <= available_pt), the difference is free
        white space.  Inserting a paragraph with space_before equal to that
        difference pushes CERTIFICATION to the foot of the page.
      - If the content overflows, no spacer is added (cert is as low as possible).
      - A 6 pt minimum threshold avoids adding a spacer for trivial amounts.
    """
    if _COVER_FIT_RESULT is None:
        return
    spacer_pt = _COVER_FIT_RESULT.available_pt - _COVER_FIT_RESULT.used_pt
    if spacer_pt > 6.0:
        p = doc.add_paragraph()
        p.paragraph_format.space_before = Pt(spacer_pt)
        p.paragraph_format.space_after  = Pt(0)
        p.add_run(" ")


# ── Certification table ───────────────────────────────────────────────────────

def _build_certification_table(body, meta):
    """
    Clean 3-row certification table.  The certification statement that was
    previously a standalone paragraph is now row 0, so the CERTIFICATION bar
    is immediately followed by this table with no intervening paragraph.

    Structure:
      Row 0  │ Certification statement — full-width merged, centered H+V
      Row 1  │ "Inspection Company:"   │ Company name + preparer + title
             │ "Report Prepared By:"  │ (cols 1+2 merged)
      Row 2  │ "Signature:"           │ blank space  │ Date
                                       ↑ right border here only

    insideV is disabled at table level; the single needed vertical divider
    (between sig-space and date in row 2) is added via _add_cell_right_border().
    """
    table = body.add_table(rows=3, cols=3)
    _apply_table_style_no_outer_vborders(table)
    _set_table_full_width(table)

    # Prevent any row of the cert table from splitting across a page boundary.
    # Combined with the conservative spacer in _build_cover_page, this ensures
    # the entire cert block stays together and on page 1.
    for row in table.rows:
        _set_row_no_split(row)

    col_widths = [Inches(2.0), Inches(4.0), Inches(1.5)]
    for row in table.rows:
        for ci, w in enumerate(col_widths):
            row.cells[ci].width = w

    cp      = _cl("table_cell_pad_pt", 1)
    body_sz = _cl("body_size_pt", STYLE_CONFIG["font_size_body"])

    # ── Row 0: Certification statement — full-width, centered ─────────────────
    cert_cell = table.cell(0, 0).merge(table.cell(0, 2))
    cert_p    = cert_cell.paragraphs[0]
    cert_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_spacing(cert_p, before=cp, after=cp)
    _style_run(cert_p.add_run(_CERT_TEXT), italic=True, size=body_sz)
    _center_cell_vertical(cert_cell)

    # ── Row 1: Inspection Company + Report Prepared By (combined) ─────────────
    # Merge value columns first, then populate both cells.
    merged_val = table.cell(1, 1).merge(table.cell(1, 2))

    lbl_cell = table.cell(1, 0)
    lp1 = lbl_cell.paragraphs[0]
    lp1.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_spacing(lp1, before=cp, after=0)
    _style_run(lp1.add_run("Inspection Company:"), bold=True, size=body_sz)
    lp2 = lbl_cell.add_paragraph()
    lp2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_spacing(lp2, before=0, after=cp)
    _style_run(lp2.add_run("Report Prepared By:"), bold=True, size=body_sz)
    _center_cell_vertical(lbl_cell)

    vp1 = merged_val.paragraphs[0]
    vp1.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_spacing(vp1, before=cp, after=0)
    _style_run(vp1.add_run(_COMPANY_NAME), size=body_sz)
    vp2 = merged_val.add_paragraph()
    vp2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_spacing(vp2, before=0, after=0)
    _style_run(vp2.add_run(meta.prepared_by or ""), size=body_sz)
    vp3 = merged_val.add_paragraph()
    vp3.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_spacing(vp3, before=0, after=cp)
    _style_run(vp3.add_run(_CERT_TITLE), italic=True, size=body_sz)
    _center_cell_vertical(merged_val)

    # ── Row 2: Signature | blank space | Date ─────────────────────────────────
    _cert_label_cell(table.cell(2, 0), "Signature:", cp, body_sz)
    _center_cell_vertical(table.cell(2, 0))

    sig_cell = table.cell(2, 1)
    sig_para = sig_cell.paragraphs[0]
    sig_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_spacing(sig_para,
                 before=_cl("cert_sig_before_pt", 12),
                 after=_cl("cert_sig_after_pt", 12))
    sig_para.add_run(" ")
    _center_cell_vertical(sig_cell)
    # Restore the single column divider between blank space and date
    _add_cell_right_border(sig_cell)

    date_cell = table.cell(2, 2)
    date_para = date_cell.paragraphs[0]
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_spacing(date_para, before=cp, after=cp)
    _style_run(date_para.add_run(f"Date: {meta.report_date or ''}"), size=body_sz)
    _center_cell_vertical(date_cell)


def _cert_label_cell(cell, text: str, cp: float = 2, body_sz: float = None):
    if body_sz is None:
        body_sz = STYLE_CONFIG["font_size_body"]
    p = cell.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER   # Fix: center text in column
    _set_spacing(p, before=cp, after=cp)
    _style_run(p.add_run(text), bold=True, size=body_sz)


def _cert_value_cell(cell, text: str, cp: float = 2, body_sz: float = None):
    if body_sz is None:
        body_sz = STYLE_CONFIG["font_size_body"]
    p = cell.paragraphs[0]
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER   # Fix: center text in column
    _set_spacing(p, before=cp, after=cp)
    lines = text.split("\n")
    for idx, line in enumerate(lines):
        if idx == 0:
            p.add_run(line)
        else:
            p.add_run("\n" + line)
        _style_run(p.runs[-1], size=body_sz)


# ══════════════════════════════════════════════════════════════════════════════
# Interior body pages
# ══════════════════════════════════════════════════════════════════════════════

def _build_inspection_body(doc: Document, proj: ProjectSession):
    _add_interior_page_header(doc, "Inspection Findings")
    _add_horizontal_rule(doc)
    _add_green_bar(doc, "INSPECTION FINDINGS")

    meta = proj.meta
    if meta.inspection_date:
        _add_body_para(doc, _FINDINGS_OPENER.format(inspection_date=meta.inspection_date))

    if not proj.systems:
        _add_body_para(doc, "No systems recorded.")
        return

    for entry in proj.systems:
        wu = proj.write_ups.get(entry.entry_id)
        sub = entry.display_name or entry.system_type
        if entry.notes:
            sub += f" - {entry.notes}"
        _add_system_subheading(doc, sub)
        if wu and wu.findings:
            _add_body_para(doc, wu.findings)
        if wu and wu.recommendations:
            _add_body_para(doc, wu.recommendations)
        _add_spacer(doc)


def _build_maintenance_body(doc: Document, proj: ProjectSession):
    _add_interior_page_header(doc, "Maintenance Summary")
    _add_horizontal_rule(doc)
    _add_green_bar(doc, "INSPECTION AND MAINTENANCE SUMMARY")

    meta         = proj.meta
    exec_summary = getattr(meta, "executive_summary", "") or ""
    _add_body_para(doc, exec_summary or meta.site_description or _SUMMARY_PLACEHOLDER)

    if not proj.systems:
        return

    for entry in proj.systems:
        wu = proj.write_ups.get(entry.entry_id)
        sub = entry.display_name or entry.system_type
        if entry.notes:
            sub += f" - {entry.notes}"
        _add_system_subheading(doc, sub)
        if wu and wu.maintenance_performed:
            _add_body_para(doc, wu.maintenance_performed)
        if wu and wu.post_service_condition:
            _add_body_para(doc, wu.post_service_condition)
        _add_spacer(doc)


def _build_combined_body(doc: Document, proj: ProjectSession):
    _add_interior_page_header(doc, "Inspection and Maintenance Summary")
    _add_horizontal_rule(doc)
    _add_green_bar(doc, "INSPECTION AND MAINTENANCE SUMMARY")

    meta         = proj.meta
    exec_summary = getattr(meta, "executive_summary", "") or ""
    _add_body_para(doc, exec_summary or meta.site_description or _SUMMARY_PLACEHOLDER)

    if not proj.systems:
        return

    for entry in proj.systems:
        wu = proj.write_ups.get(entry.entry_id)
        sub = entry.display_name or entry.system_type
        if entry.notes:
            sub += f" - {entry.notes}"
        _add_system_subheading(doc, sub)
        if wu and wu.findings:
            _add_body_para(doc, wu.findings)
        if wu and wu.maintenance_performed:
            _add_body_para(doc, wu.maintenance_performed)
        if wu and wu.post_service_condition:
            _add_body_para(doc, wu.post_service_condition)
        if wu and wu.recommendations:
            _add_body_para(doc, wu.recommendations)
        _add_spacer(doc)


# ══════════════════════════════════════════════════════════════════════════════
# Photo section  (Fixes #8 #9 #10 #11 #12)
# ══════════════════════════════════════════════════════════════════════════════

def _estimate_photo_header_height_pt() -> float:
    """
    Conservative over-estimate of the photo page Row 0 height:
    logo paragraph + label paragraph + top black rule paragraph.
    """
    try:
        from PIL import Image as _PILImg
        img = _PILImg.open(str(_LOGO_PATH))
        w_px, h_px = img.size
        aspect = w_px / max(h_px, 1)
    except Exception:
        aspect = 3.296   # Sterling logo fallback
    logo_h   = (_PHOTO_LOGO_WIDTH / aspect) * 72.0 + 2.0   # image height + after=2
    label_h  = 10.0 * 1.20 + 2.0    # 10 pt bold line + before=2
    rule_h   = 8.5  * 1.20 + 4.0    # Normal-style para + after=4
    return logo_h + label_h + rule_h + 6.0   # +6 pt safety


def _build_photo_section(doc: Document, proj: ProjectSession, grid_type: str = "2x3"):
    """
    Continuous photo sheets across ALL systems.

    Photos from all systems are merged into one ordered stream (sorted by
    system position then display_order within each system), then batched
    into pages of `per_page` photos each.

    Each page uses a 3-row borderless layout table (same structural approach
    as the cover page):
      Row 0  fixed   logo header + label + top black rule
      Row 1  flex    photo grid  (exact height = remaining body space)
      Row 2  fixed   bottom black rule  (structurally anchored — no spacer)

    The bottom black rule is in Row 2 by construction; it never orphans onto
    a blank page regardless of how many photos are on the page.
    """
    cfg         = _GRID_CFG.get(grid_type, _GRID_CFG["2x3"])
    cols        = cfg["cols"]
    per_page    = cfg["per_page"]
    col_w       = cfg["col_w"]
    photo_w     = cfg["photo_w"]
    photo_h_max = cfg["photo_h_max"]
    rows_pp     = cfg["rows"]

    if not proj.photos:
        return

    # ── Build one flat ordered list: system order → display_order ────────────
    system_order = {s.entry_id: i for i, s in enumerate(proj.systems)}
    all_photos = sorted(
        proj.photos,
        key=lambda p: (system_order.get(p.system_entry_id, 9999), p.display_order),
    )

    # ── Batch across all photos continuously ─────────────────────────────────
    batches = [all_photos[i:i + per_page] for i in range(0, len(all_photos), per_page)]

    # Pre-compute photo page row heights (same for every batch).
    # Row 0: logo + label + top rule (fixed, over-estimated)
    # Row 2: bottom black rule (fixed, generous)
    # Row 1: remaining body space (absorbs everything else)
    _PHOTO_OVERHEAD_PT = 4.0   # table rendering overhead (no leading blank para on photo pages)
    _photo_row0_h = _estimate_photo_header_height_pt()
    _photo_row2_h = 18.0   # bottom rule: generous — actual ~14 pt, extra anchors it safely
    _photo_row1_h = max(10.0,
                        _BODY_HEIGHT_PT - _PHOTO_OVERHEAD_PT - _photo_row0_h - _photo_row2_h)

    print(f"[photo-table] row0={_photo_row0_h:.1f}  row1={_photo_row1_h:.1f}  "
          f"row2={_photo_row2_h:.1f}  total={_photo_row0_h+_photo_row1_h+_photo_row2_h:.1f}  "
          f"body={_BODY_HEIGHT_PT:.1f}")

    for batch in batches:
        doc.add_page_break()

        # ── Phase 1: build all photo-page content in flat doc flow ────────────
        body_el   = doc.element.body
        _snap0_set = set(body_el)   # snapshot AFTER page break (includes break para)

        # Row 0 content: logo + label + top rule
        _add_photo_page_logo_header(doc)
        lbl = doc.add_paragraph()
        _set_spacing(lbl, before=2, after=0)
        _style_run(lbl.add_run("Service Photos Are Provided Below:"), bold=True, size=10)
        _add_black_rule(doc)

        _snap1_list = list(body_el)
        _snap1_set  = set(_snap1_list)

        # Row 1 content: photo grid
        _build_photo_grid_table(doc, batch, cols, col_w, photo_w, photo_h_max, rows_pp)

        _snap2_list = list(body_el)
        _snap2_set  = set(_snap2_list)

        # Row 2 content: bottom black rule
        _add_black_rule(doc)

        _snap3_list = list(body_el)

        # ── Phase 2: classify elements by destination row ─────────────────────
        row0_elems = [e for e in _snap1_list if e not in _snap0_set]
        row1_elems = [e for e in _snap2_list if e not in _snap1_set]
        row2_elems = [e for e in _snap3_list if e not in _snap2_set]

        # ── Phase 3: remove classified elements from body ─────────────────────
        for elem in row0_elems + row1_elems + row2_elems:
            body_el.remove(elem)

        # ── Phase 4: create 3-row borderless outer layout table ───────────────
        outer = doc.add_table(rows=3, cols=1)
        _remove_table_borders(outer)
        _set_table_full_width(outer)
        _zero_table_cell_spacing(outer)

        for row, h in [(outer.rows[0], _photo_row0_h),
                       (outer.rows[1], _photo_row1_h),
                       (outer.rows[2], _photo_row2_h)]:
            _set_row_min_height(row, h, rule="exact")
            _zero_all_cell_margins(row.cells[0])

        # ── Phase 5: inject content into cells ────────────────────────────────
        _inject_into_cell(outer.rows[0].cells[0], row0_elems)
        _inject_into_cell(outer.rows[1].cells[0], row1_elems)
        _inject_into_cell(outer.rows[2].cells[0], row2_elems)


def _add_photo_page_logo_header(doc: Document):
    """
    Fix #11: no section title text on photo pages.
    Fix #12: logo at _PHOTO_LOGO_WIDTH = 3.0" (2× original 1.5").
    """
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    _set_spacing(p, before=0, after=2)
    run = p.add_run()
    if _LOGO_PATH.exists():
        run.add_picture(str(_LOGO_PATH), width=Inches(_PHOTO_LOGO_WIDTH))
    else:
        run.text = "Sterling"
        _style_run(run, bold=True, size=16, color=STYLE_CONFIG["color_primary"])


def _build_photo_grid_table(doc: Document, batch: list,
                             cols: int, col_w: float,
                             photo_w: float, photo_h_max: float,
                             rows_per_page: int):
    """
    Single multi-row table for one page of photos.
    Structure: for each photo row → [img row] then [caption row].
    Fix #10: _get_display_size() prevents portrait overflow.
    """
    per_page = cols * rows_per_page
    padded   = list(batch)
    while len(padded) < per_page:
        padded.append(None)

    n_tbl_rows = rows_per_page * 2   # img + caption per photo row
    table = doc.add_table(rows=n_tbl_rows, cols=cols)
    _remove_table_borders(table)

    for row in table.rows:
        for c in range(cols):
            row.cells[c].width = Inches(col_w)

    photo_idx = 0
    for pr in range(rows_per_page):
        img_ri = pr * 2
        cap_ri = pr * 2 + 1

        for c in range(cols):
            photo = padded[photo_idx] if photo_idx < len(padded) else None
            photo_idx += 1

            img_para = table.cell(img_ri, c).paragraphs[0]
            img_para.alignment = WD_ALIGN_PARAGRAPH.LEFT   # Fix: left-align so photo left edge = caption left edge
            _set_spacing(img_para, before=2, after=2)

            cap_para = table.cell(cap_ri, c).paragraphs[0]
            cap_para.alignment = WD_ALIGN_PARAGRAPH.LEFT
            _set_spacing(cap_para, before=2, after=4)

            if photo is None:
                img_para.add_run(" ")
                cap_para.add_run(" ")
                continue

            img_bytes = _load_photo_bytes(photo)
            if img_bytes:
                try:
                    disp_w, disp_h = _get_display_size(img_bytes, photo_w, photo_h_max)
                    img_stream = io.BytesIO(img_bytes)
                    img_run    = img_para.add_run()
                    # Use height constraint when photo is portrait, width otherwise
                    if disp_w < photo_w - 0.05:
                        img_run.add_picture(img_stream, height=Inches(disp_h))
                    else:
                        img_run.add_picture(img_stream, width=Inches(disp_w))
                except Exception as exc:
                    _style_run(img_para.add_run(f"[Error: {str(exc)[:60]}]"),
                               italic=True, size=8)
            else:
                _style_run(img_para.add_run(f"[Not found: {photo.filename}]"),
                           italic=True, size=8, color=RGBColor(0x99, 0x99, 0x99))

            caption  = photo.caption_override or photo.computed_caption()
            cap_run  = cap_para.add_run(caption)
            # Fix: Calibri (Headings), bold, 10pt
            _style_run(cap_run, bold=True, size=10)
            cap_run.font.name = "Calibri"   # was Arial Black


def _get_display_size(img_bytes: bytes, max_w: float, max_h: float):
    """
    Fix #10: compute display (width, height) in inches that fits within
    max_w × max_h while maintaining the image's natural aspect ratio.
    Prevents portrait photos from overflowing cell height.
    """
    try:
        from PIL import Image as _PILImg
        img = _PILImg.open(io.BytesIO(img_bytes))
        nat_w, nat_h = img.size
        if nat_h == 0:
            return max_w, max_h
        aspect = nat_w / nat_h          # > 1 landscape, < 1 portrait
        h_at_max_w = max_w / aspect
        if h_at_max_w <= max_h:
            return max_w, h_at_max_w    # width is binding
        return max_h * aspect, max_h    # height is binding
    except Exception:
        return max_w, max_h             # fallback: width only


def _load_photo_bytes(photo) -> bytes | None:
    p = Path(photo.filepath)
    if p.exists():
        try:
            return resize_for_report(str(p))
        except Exception:
            return p.read_bytes()
    return None


# ══════════════════════════════════════════════════════════════════════════════
# Footer  (Fix #4: 10 pt throughout)
# ══════════════════════════════════════════════════════════════════════════════

def _add_footer(section):
    """Contact line + Page X of Y, both at 10 pt (Fix #4)."""
    footer = section.footer
    footer.is_linked_to_previous = False

    for para in footer.paragraphs:
        for run in para.runs:
            run.text = ""

    contact_para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
    contact_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_spacing(contact_para, before=0, after=2)
    _style_run(
        contact_para.add_run(
            f"Please contact {_COMPANY_EMAIL} with questions or comments "
            "regarding the information provided."
        ),
        size=10,   # Fix #4
    )

    page_para = footer.add_paragraph()
    page_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_spacing(page_para, before=0, after=0)
    _append_field_run(page_para, " PAGE ",     size=10)   # Fix #4
    _style_run(page_para.add_run(" of "),      size=10)
    _append_field_run(page_para, " NUMPAGES ", size=10)   # Fix #4


def _append_field_run(para, instr_text: str, size: int = 10):
    run = para.add_run()
    _style_run(run, size=size)
    r = run._r
    begin = OxmlElement("w:fldChar");  begin.set(qn("w:fldCharType"), "begin");  r.append(begin)
    instr = OxmlElement("w:instrText"); instr.set(qn("xml:space"), "preserve");  instr.text = instr_text; r.append(instr)
    end   = OxmlElement("w:fldChar");  end.set(qn("w:fldCharType"), "end");    r.append(end)


# ══════════════════════════════════════════════════════════════════════════════
# Shared formatting primitives
# ══════════════════════════════════════════════════════════════════════════════

def _add_green_bar(body, text: str):
    """
    Green section bar.
    `body` may be a Document (document body) or a Cell (nested inside a
    layout-table cell) — both expose add_table() / add_paragraph().
    """
    table = body.add_table(rows=1, cols=1)
    _remove_table_borders(table)
    _set_table_full_width(table)      # Fix: spans same width as info tables
    cell = table.cell(0, 0)
    _shade_cell(cell, _STERLING_GREEN)
    _add_cell_top_bottom_borders(cell, "000000", sz=12)   # Fix: 2× thickness
    _zero_cell_tb_margins(cell)       # Fix: 25% thinner — zero internal cell padding

    para = cell.paragraphs[0]
    para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    _set_spacing(para, before=0, after=0)   # Fix: 25% thinner — no paragraph padding
    _style_run(para.add_run(text.upper()),
               bold=True, size=10,
               color=RGBColor(0x00, 0x00, 0x00))
    # IMPORTANT: Do NOT add _add_spacer() here — it creates a visible blank line
    # between the bar and the following content (Fix #1).  The following content's
    # own space_before provides sufficient visual separation.


def _add_thick_green_footer_bar(body):
    """
    Solid filled green bar at the bottom of the cover page.
    `body` accepts Document or Cell — see _add_green_bar docstring.
    """
    table = body.add_table(rows=1, cols=1)
    _remove_table_borders(table)
    _set_table_full_width(table)
    cell = table.cell(0, 0)
    _shade_cell(cell, _STERLING_GREEN)
    _add_cell_top_bottom_borders(cell, "000000", sz=12)   # matching bar thickness
    _zero_cell_tb_margins(cell)       # Fix: 25% thinner — zero internal cell padding
    para = cell.paragraphs[0]
    _set_spacing(para, before=2, after=2)   # Fix: 25% thinner (was 3/3)
    para.add_run(" ")   # no text — solid green block


def _add_interior_page_header(doc: Document, section_title: str):
    """2-col borderless header: logo left, green bold title right."""
    table = doc.add_table(rows=1, cols=2)
    _remove_table_borders(table)
    lc = table.cell(0, 0);  lc.width = Inches(2.0)
    rc = table.cell(0, 1);  rc.width = Inches(4.5)

    lp = lc.paragraphs[0]
    lp.alignment = WD_ALIGN_PARAGRAPH.LEFT
    _set_spacing(lp, before=0, after=0)
    lr = lp.add_run()
    if _LOGO_PATH.exists():
        lr.add_picture(str(_LOGO_PATH), width=Inches(_INTERIOR_LOGO_WIDTH))
    else:
        lr.text = "Sterling"
        _style_run(lr, bold=True, color=STYLE_CONFIG["color_primary"])

    rp = rc.paragraphs[0]
    rp.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    _set_spacing(rp, before=6, after=0)
    _style_run(rp.add_run(section_title), bold=True, size=12,
               color=STYLE_CONFIG["color_primary"])


def _add_horizontal_rule(doc: Document, color: str = None):
    """
    Thin horizontal rule via paragraph bottom border.
    color: 6-char hex (default: _STERLING_GREEN for interior pages).
    Use "000000" for black rules on photo pages.
    """
    if color is None:
        color = _STERLING_GREEN
    p = doc.add_paragraph()
    _set_spacing(p, before=0, after=4)
    pPr  = p._p.get_or_add_pPr()
    pBdr = OxmlElement("w:pBdr")
    bot  = OxmlElement("w:bottom")
    bot.set(qn("w:val"),   "single")
    bot.set(qn("w:sz"),    "6")
    bot.set(qn("w:space"), "1")
    bot.set(qn("w:color"), color)
    pBdr.append(bot)
    pPr.append(pBdr)


def _add_black_rule(doc: Document):
    """Fix #8: Black horizontal rule for photo page separators."""
    _add_horizontal_rule(doc, color="000000")


def _add_system_subheading(doc: Document, text: str):
    """Interior page system subheading: underlined bold body text."""
    p = doc.add_paragraph()
    _set_spacing(p, before=8, after=2)
    run = p.add_run(text)
    run.font.name      = STYLE_CONFIG["font_heading"]
    run.font.size      = Pt(STYLE_CONFIG["font_size_body"])
    run.font.bold      = True
    run.font.underline = True


def _add_cover_system_subheading(body, text: str):
    """Cover page system subheading — spacing driven by page-fit algorithm."""
    p = body.add_paragraph()
    _set_spacing(p,
                 before=_cl("subhead_before_pt", 3),
                 after=_cl("subhead_after_pt", 1))
    run = p.add_run(text)
    run.font.name      = STYLE_CONFIG["font_heading"]
    run.font.size      = Pt(_cl("body_size_pt", STYLE_CONFIG["font_size_body"]))
    run.font.bold      = True
    run.font.underline = True


def _add_body_para(doc: Document, text: str):
    """Interior page body paragraph (normal spacing: 2 before, 4 after)."""
    for block in text.strip().split("\n\n"):
        combined = " ".join(ln.strip() for ln in block.strip().split("\n") if ln.strip())
        if not combined:
            continue
        p = doc.add_paragraph()
        _set_spacing(p, before=2, after=4)
        _style_run(p.add_run(combined), size=STYLE_CONFIG["font_size_body"])


def _add_cover_body_para(body, text: str):
    """Cover page body paragraph — spacing driven by page-fit algorithm."""
    for block in text.strip().split("\n\n"):
        combined = " ".join(ln.strip() for ln in block.strip().split("\n") if ln.strip())
        if not combined:
            continue
        p = body.add_paragraph()
        _set_spacing(p,
                     before=_cl("body_before_pt", 0),
                     after=_cl("body_after_pt", 2))
        _style_run(p.add_run(combined),
                   size=_cl("body_size_pt", STYLE_CONFIG["font_size_body"]))


def _add_spacer(doc: Document, height: int = 0):
    p = doc.add_paragraph()
    _set_spacing(p, before=height, after=height)


def _set_spacing(para, before: int = 0, after: int = 0):
    para.paragraph_format.space_before = Pt(before)
    para.paragraph_format.space_after  = Pt(after)


def _style_run(run, bold: bool = False, italic: bool = False,
               size: float = None, color: RGBColor = None):
    if size is None:
        size = STYLE_CONFIG["font_size_body"]
    run.font.name   = STYLE_CONFIG["font_body"]
    run.font.size   = Pt(size)
    run.font.bold   = bold
    run.font.italic = italic
    if color is not None:
        run.font.color.rgb = color
    return run


def _shade_cell(cell, hex_color: str):
    tc   = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd  = OxmlElement("w:shd")
    shd.set(qn("w:val"),   "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"),  hex_color)
    tcPr.append(shd)


def _add_cell_top_bottom_borders(cell, hex_color: str, sz: int = 6):
    """
    Fix #2: Add top and bottom border lines to a cell.
    Used to create black overline/underline on green section bars.
    """
    tc   = cell._tc
    tcPr = tc.get_or_add_tcPr()
    tcBorders = OxmlElement("w:tcBorders")
    for edge in ("top", "bottom"):
        el = OxmlElement(f"w:{edge}")
        el.set(qn("w:val"),   "single")
        el.set(qn("w:sz"),    str(sz))
        el.set(qn("w:space"), "0")
        el.set(qn("w:color"), hex_color)
        tcBorders.append(el)
    existing = tcPr.find(qn("w:tcBorders"))
    if existing is not None:
        tcPr.remove(existing)
    tcPr.append(tcBorders)


def _add_cell_right_border(cell, hex_color: str = "000000", sz: int = 12):
    """
    Add a right-side border to one specific cell.
    Used to restore a single column divider after insideV is globally hidden.
    Preserves any existing top/bottom borders already set on the cell.
    """
    tc    = cell._tc
    tcPr  = tc.get_or_add_tcPr()
    tcBdr = tcPr.find(qn("w:tcBorders"))
    if tcBdr is None:
        tcBdr = OxmlElement("w:tcBorders")
        tcPr.append(tcBdr)
    existing = tcBdr.find(qn("w:right"))
    if existing is not None:
        tcBdr.remove(existing)
    el = OxmlElement("w:right")
    el.set(qn("w:val"),   "single")
    el.set(qn("w:sz"),    str(sz))
    el.set(qn("w:space"), "0")
    el.set(qn("w:color"), hex_color)
    tcBdr.append(el)


def _add_exact_spacer(body, spacer_pt: float):
    """
    Insert a paragraph whose height is exactly `spacer_pt` points.

    Uses w:lineRule="exact" so the paragraph occupies precisely spacer_pt with
    no run-level line-height added on top (unlike space_before, which adds the
    default font's line height ~10 pt beyond the requested spacing value).

    Used for bottom-pinning the Certification block (cover page) and the bottom
    black rule (photo pages).
    """
    if spacer_pt <= 1.0:
        return
    sp = body.add_paragraph()
    pPr = sp._p.get_or_add_pPr()
    spc = OxmlElement("w:spacing")
    spc.set(qn("w:before"),   "0")
    spc.set(qn("w:after"),    "0")
    spc.set(qn("w:line"),     str(int(spacer_pt * 20)))   # 20 twips per point
    spc.set(qn("w:lineRule"), "exact")
    pPr.append(spc)
    # 1-pt font prevents Word from expanding the exact-height line for large
    # default paragraph fonts.
    rPr = OxmlElement("w:rPr")
    for tag in ("w:sz", "w:szCs"):
        el = OxmlElement(tag)
        el.set(qn("w:val"), "2")   # 2 half-points = 1 pt
        rPr.append(el)
    pPr.append(rPr)


def _minimize_trailing_para(doc: Document):
    """
    python-docx / OOXML requires a paragraph as the last body element.
    When the final content element is a table (e.g. the footer green bar),
    this mandatory trailing paragraph can overflow page 1 and produce a
    blank page 2.  Fix: collapse it to an exact 1-point line so it occupies
    negligible vertical space.
    Only acts on paragraphs with no visible text content.
    """
    if not doc.paragraphs:
        return
    last = doc.paragraphs[-1]
    if last.text.strip():   # non-empty → real content, don't touch
        return
    last.paragraph_format.space_before = Pt(0)
    last.paragraph_format.space_after  = Pt(0)
    pPr = last._p.get_or_add_pPr()
    # Remove any existing spacing element then re-add with exact 1-pt line
    for child in list(pPr):
        if child.tag == qn("w:spacing"):
            pPr.remove(child)
    sp = OxmlElement("w:spacing")
    sp.set(qn("w:before"),  "0")
    sp.set(qn("w:after"),   "0")
    sp.set(qn("w:line"),    "20")      # 20 twips = 1 pt
    sp.set(qn("w:lineRule"), "exact")
    pPr.append(sp)
    # Collapse the paragraph's default run font to 1 pt
    rPr = pPr.find(qn("w:rPr"))
    if rPr is None:
        rPr = OxmlElement("w:rPr")
        pPr.append(rPr)
    for tag in ("w:sz", "w:szCs"):
        existing = rPr.find(qn(tag))
        if existing is not None:
            rPr.remove(existing)
        el = OxmlElement(tag)
        el.set(qn("w:val"), "2")   # 2 half-points = 1 pt
        rPr.append(el)


def _clear_cell_para(cell):
    """
    Remove the default empty paragraph(s) python-docx inserts into every
    new table cell.  Called before adding content to a layout-table cell so
    no stray blank line appears before the first real element.
    """
    tc = cell._tc
    for p in list(tc.findall(qn("w:p"))):
        if not p.findall(qn("w:r")):   # no runs → empty paragraph
            tc.remove(p)


def _set_row_no_split(row):
    """
    Prevent a table row from splitting across a page boundary (w:cantSplit).
    Applied to the certification row of the outer layout table so the entire
    cert section is guaranteed to stay on page 1 as one unit.
    """
    tr   = row._tr
    trPr = tr.get_or_add_trPr()
    existing = trPr.find(qn("w:cantSplit"))
    if existing is not None:
        trPr.remove(existing)
    cant = OxmlElement("w:cantSplit")
    cant.set(qn("w:val"), "1")
    trPr.append(cant)


def _center_cell_vertical(cell):
    """Set vertical alignment to center on a table cell (w:vAlign = center)."""
    tc   = cell._tc
    tcPr = tc.get_or_add_tcPr()
    vAlign = OxmlElement("w:vAlign")
    vAlign.set(qn("w:val"), "center")
    existing = tcPr.find(qn("w:vAlign"))
    if existing is not None:
        tcPr.remove(existing)
    tcPr.append(vAlign)


def _set_row_min_height(row, height_pt: float, rule: str = "atLeast"):
    """Set a minimum (or exact) row height in points via w:trHeight."""
    tr   = row._tr
    trPr = tr.get_or_add_trPr()
    trH  = OxmlElement("w:trHeight")
    trH.set(qn("w:val"),   str(int(height_pt * 20)))   # 1 pt = 20 twips
    trH.set(qn("w:hRule"), rule)
    existing = trPr.find(qn("w:trHeight"))
    if existing is not None:
        trPr.remove(existing)
    trPr.append(trH)


def _zero_all_cell_margins(cell):
    """
    Zero all four internal cell margins (top, bottom, left, right) on a cell.
    Used on outer layout-table cells to eliminate Word's default ~115-twip
    cell padding from contributing hidden height to the layout rows.
    """
    tc   = cell._tc
    tcPr = tc.get_or_add_tcPr()
    tcMar = OxmlElement("w:tcMar")
    for edge in ("top", "left", "bottom", "right"):
        el = OxmlElement(f"w:{edge}")
        el.set(qn("w:w"),    "0")
        el.set(qn("w:type"), "dxa")
        tcMar.append(el)
    existing = tcPr.find(qn("w:tcMar"))
    if existing is not None:
        tcPr.remove(existing)
    tcPr.append(tcMar)


def _zero_cell_tb_margins(cell):
    """Zero the top and bottom internal cell margins (w:tcMar) to slim green bars."""
    tc   = cell._tc
    tcPr = tc.get_or_add_tcPr()
    tcMar = OxmlElement("w:tcMar")
    for edge in ("top", "bottom"):
        el = OxmlElement(f"w:{edge}")
        el.set(qn("w:w"),    "0")
        el.set(qn("w:type"), "dxa")
        tcMar.append(el)
    existing = tcPr.find(qn("w:tcMar"))
    if existing is not None:
        tcPr.remove(existing)
    tcPr.append(tcMar)


def _inject_into_cell(cell, elems):
    """
    Move lxml elements into a table cell, inserting them before the trailing
    mandatory <w:p> that python-docx puts in every new cell.

    Shared by both _build_cover_page (Phase 6) and _build_photo_section
    (Phase 5) so the XML-rearrange pattern is implemented in one place.
    """
    tc = cell._tc
    # Find the last direct-child <w:p> — that is the mandatory trailing para.
    last_p = None
    for child in tc:
        if child.tag == qn("w:p"):
            last_p = child
    for elem in elems:
        if last_p is not None:
            tc.insert(list(tc).index(last_p), elem)
        else:
            tc.append(elem)


def _zero_table_cell_spacing(table):
    """
    Explicitly set w:tblCellSpacing to 0 so the inherited table style does
    not add hidden inter-row height to layout tables.
    """
    tblPr = table._tbl.tblPr
    if tblPr is None:
        tblPr = OxmlElement("w:tblPr")
        table._tbl.insert(0, tblPr)
    existing = tblPr.find(qn("w:tblCellSpacing"))
    if existing is not None:
        tblPr.remove(existing)
    cs = OxmlElement("w:tblCellSpacing")
    cs.set(qn("w:w"),    "0")
    cs.set(qn("w:type"), "dxa")
    tblPr.append(cs)


def _set_table_full_width(table):
    """
    Force a table to span the full usable page width (7.5" = 10800 twips).
    Ensures info tables and green bars all share the same left/right edges.
    """
    tbl   = table._tbl
    tblPr = tbl.tblPr
    if tblPr is None:
        tblPr = OxmlElement("w:tblPr")
        tbl.insert(0, tblPr)
    existing = tblPr.find(qn("w:tblW"))
    if existing is not None:
        tblPr.remove(existing)
    tblW = OxmlElement("w:tblW")
    tblW.set(qn("w:w"),    "10800")   # 7.5" × 1440 twips/inch
    tblW.set(qn("w:type"), "dxa")
    tblPr.append(tblW)


def _apply_table_style_no_outer_vborders(table):
    """
    Fix #5: Set table borders so that:
    - Top / bottom outer borders: visible (single black)
    - Left / right outer borders: HIDDEN (none)
    - InsideH / InsideV: visible (single black)
    Replaces 'Table Grid' which shows all six borders.
    """
    tbl   = table._tbl
    tblPr = tbl.tblPr
    if tblPr is None:
        tblPr = OxmlElement("w:tblPr")
        tbl.insert(0, tblPr)

    tblBorders = OxmlElement("w:tblBorders")

    # Horizontal rules (top, bottom, row dividers) — visible, 2× thickness
    for edge in ("top", "bottom", "insideH"):
        el = OxmlElement(f"w:{edge}")
        el.set(qn("w:val"),   "single")
        el.set(qn("w:sz"),    "12")   # 2× thickness
        el.set(qn("w:space"), "0")
        el.set(qn("w:color"), "000000")
        tblBorders.append(el)

    # Vertical rules — ALL hidden at table level.
    # Column dividers are added selectively via _add_cell_right_border()
    # so only the specific column boundary the design requires is shown.
    for edge in ("left", "right", "insideV"):
        el = OxmlElement(f"w:{edge}")
        el.set(qn("w:val"),   "none")
        el.set(qn("w:sz"),    "0")
        el.set(qn("w:space"), "0")
        el.set(qn("w:color"), "auto")
        tblBorders.append(el)

    existing = tblPr.find(qn("w:tblBorders"))
    if existing is not None:
        tblPr.remove(existing)
    tblPr.append(tblBorders)


def _remove_table_borders(table):
    """Fully borderless table (used for layout tables: logo headers, photo grids)."""
    tbl   = table._tbl
    tblPr = tbl.tblPr
    if tblPr is None:
        tblPr = OxmlElement("w:tblPr")
        tbl.insert(0, tblPr)

    tblBorders = OxmlElement("w:tblBorders")
    for edge in ("top", "left", "bottom", "right", "insideH", "insideV"):
        el = OxmlElement(f"w:{edge}")
        el.set(qn("w:val"),   "none")
        el.set(qn("w:sz"),    "0")
        el.set(qn("w:space"), "0")
        el.set(qn("w:color"), "auto")
        tblBorders.append(el)

    existing = tblPr.find(qn("w:tblBorders"))
    if existing is not None:
        tblPr.remove(existing)
    tblPr.append(tblBorders)
