"""initial schema

Revision ID: 983d679c89ea
Revises: 
Create Date: 2026-04-16 16:40:44.279593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983d679c89ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'admin', 'inspector', 'reviewer', 'technician', 'client_portal', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('contacts',
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_index(op.f('ix_contacts_client_id'), 'contacts', ['client_id'], unique=False)
    op.create_table('sites',
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('site_id'),
    sa.UniqueConstraint('client_id', 'name', name='uq_site_client_name')
    )
    op.create_index(op.f('ix_sites_client_id'), 'sites', ['client_id'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('report_number', sa.String(), nullable=True),
    sa.Column('inspection_date', sa.String(), nullable=True),
    sa.Column('report_date', sa.String(), nullable=True),
    sa.Column('prepared_by', sa.String(), nullable=True),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('condition_summary', sa.String(), nullable=True),
    sa.Column('session_json_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index('idx_reports_date', 'reports', ['report_date'], unique=False)
    op.create_index('idx_reports_inspector', 'reports', ['created_by'], unique=False)
    op.create_index('idx_reports_site', 'reports', ['site_id'], unique=False)
    op.create_table('site_notes',
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_site_notes_site_id'), 'site_notes', ['site_id'], unique=False)
    op.create_table('user_site_assignments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'site_id')
    )
    op.create_table('files',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('stored_path', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_index('idx_files_report', 'files', ['report_id'], unique=False)
    op.create_index('idx_files_site', 'files', ['site_id'], unique=False)
    op.create_table('system_conditions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('system_id', sa.String(), nullable=True),
    sa.Column('system_type', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.report_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_syscond_report', 'system_conditions', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_syscond_report', table_name='system_conditions')
    op.drop_table('system_conditions')
    op.drop_index('idx_files_site', table_name='files')
    op.drop_index('idx_files_report', table_name='files')
    op.drop_table('files')
    op.drop_table('user_site_assignments')
    op.drop_index(op.f('ix_site_notes_site_id'), table_name='site_notes')
    op.drop_table('site_notes')
    op.drop_index('idx_reports_site', table_name='reports')
    op.drop_index('idx_reports_inspector', table_name='reports')
    op.drop_index('idx_reports_date', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_sites_client_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_contacts_client_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
